### ISSUE TITLE
tabs and spaces

### ISSUE THREAD

**Issue by majkelx** [PBrus/Standard-photometry#1]
Mam błąd

  File "/Users/mka/projects/astro/stand-photo/make_std_phot.py", line 115
    ax.col_data.ok[event.ind] = not ax.col_data.ok[event.ind].any() ## if any point is ok change to rejected
                                                                                                           ^
TabError: inconsistent use of tabs and spaces in indentation

(poprawię)

**Comment by pbrus** [comment]
I prefer to use tabulators, not a single space character. Previous version contained mainly space characters and new lines were added according to my style. Unification should be used. I'll standardize the whole code in the nearest future.

**Comment by majkelx** [comment]
I have switched for tabs for this project, and changed existing space-indents in #3
